### ISSUE TITLE
Custom array constructor not working with `each`

### ISSUE THREAD

**Issue by DawidJanczak** [dry-rb/dry-schema#286]
**Describe the bug**

It's not possible to use a particular custom array constructor with `each` macro.

**To Reproduce**

See https://discourse.dry-rb.org/t/preprocessing-certain-fields-in-a-schema/1048 and https://github.com/DawidJanczak/dry-validation-custom-array-type/blob/master/test.rb

**Expected behavior**

I expect each to work with custom array constructor.

**Your environment**

- Affects my production application: **YES**
- Ruby version: 2.6.2p47
- OS: Arch Linux

**Comment by solnic** [comment]
@DawidJanczak OK I finally dug into it and this is actually something that cannot be fixed because this type of coercion cannot be handled at the type schema level. You need to either load this string io + parse with JSON before passing to the schema or experiment with `before` steps to do the same.

This is what happens:

1) schema's key map processes the input and only handles `items` key, becauase the rest is a string io object
2) your custom type loads string io and parses it with JSON, so now you have a hash but its keys are strings not symbols and now it's too late to coerce them to symbols because it happens in step 1
3) schema rules are applied and they don't find expected keys because they are not symbols, so you get errors

We should somehow document it, because I can see how people can be confused by this behavior.

**Comment by DawidJanczak** [comment]
Thanks for looking into this, makes sense.

**Comment by solnic** [comment]
I reported #287 as a follow-up. Closing this one as invalid.
