### ISSUE TITLE
Built-in predicate names

### ISSUE THREAD

**Issue by kstenerud** [dry-rb/dry-schema#46]
The names chosen for some of the built-in predicates don't match those commonly used in other languages, increasing cognitive load and the potential for user error. Please consider using the common names instead:

| dry | common |
| --- | ---------- |
| eql | eq |
| gt | gt |
| gteq | ge |
| lt | lt |
| lteq | le |

**Comment by igor-alexandrov** [comment]
Arel has `eq`, `gteq` and `lteq`: https://www.rubydoc.info/github/rails/arel/Arel/Predications.

Based on my experience, I think that `eql` can be confusing, but `gteq` and `lteq` are common used in Ruby.

**Comment by solnic** [comment]
Given that we have 4 years of history with these predicates, I don't think it's worth the effort to change it now, especially that:

- `gteq?` and `lteq?` are used in other gems
- `eql?` is called `eql?` because it **uses Object#eql?** which makes a lot of sense, let's be consistent with the method name especially that there are differences in behavior between `==` and `eql?`
