### ISSUE TITLE
change keys after validation

### ISSUE THREAD

**Issue by HoneyryderChuck** [dry-rb/dry-schema#73]
I'd like to have the ability to change a key for the success case, to that:

```ruby
params = {address: {city: "London"}}
result = schema.call(params)
result.output => {"address_attributes" => {"city" => "London" }}
```

As you might have guessed, I'm trying to make active record nested assignment happen :)

**Comment by solnic** [comment]
This is not the right place to do this type of transformations. `dry-schema` is focused purely on parsing and validating data, any data transformation logic should be handled by something else. It shouldn't be too hard to build a gem that make dry-schema play nice with AR. It would be worth looking into using dry-validation 1.0.0 too, because it will provide more features that could replace AR's validation. You basically need a validation contract + a data transformer (we have `transproc` gem that has a ton of data transformation functions that can be composed) + something that will pass data to AR model.

If you want to explore this further and discuss, please open a new thread on discourse.dry-rb.org. We try to use issues only for bug reports and confirmed feature requests. See `CONTRIBUTING.md` for more info.

**Comment by HoneyryderChuck** [comment]
> It would be worth looking into using dry-validation 1.0.0 too, because it will provide more features that could replace AR's validation.

Personally, I'm more interested in just doing schema validation and not mixing AR-style validations (that's what trailblazer contracts do, and IMO it's a big mess).

I will have a look on that transproc reference, let's see if it does the trick. Thx!
