### ISSUE TITLE
Why not support ruby 2.3?

### ISSUE THREAD

**Issue by HoneyryderChuck** [dry-rb/dry-schema#77]
The same could be said of ruby 2.2 .

For context: I'm in the process of porting an outdated dry-validation integration to dry-schema. I tried first with 0.1.1, but ran into the bug related with the error messages not being consistent with nested schemas. I've seen the changelog mentions for 0.2.0, and wanted to give it a try, but this project runs ruby 2.3, so no can do.

Now, migrating to ruby 2.4 is way less trivial than migrating our schema validators (it's a fairly big app). And I don't know exactly what features depend on ruby 2.4 tbh. Are there any? Because unless these fixes are backported to 0.1.x, I'll be stuck with unsupported `dry-validation` until we migrate to 2.4, which might take some time. :/

**Comment by solnic** [comment]
I'm sorry but we're dropping support for 2.3 here and in other dry-rb gems too. 2.3 is being EOLed in a month from now.

**Comment by HoneyryderChuck** [comment]
I'm totally fine with not committing to supporting 2.3 because it's eol, but. Since you don't seem to target any 2.4-specific feature, why can't you just remove the ruby version constraint, like "we target 2.4, but it might work in 2.3"?

**Comment by solnic** [comment]
Yes we could do that, I definitely don't want to block anybody, if this can be clearly communicated then I'm fine with it. WDYT @timriley @flash-gordon ?

**Comment by timriley** [comment]
If going a version back is not causing test failures, i.e. if it's not a drag on our development and maintenance efforts, I'm OK for us to do it.

That said, I certainly support the policy of only _officially_ supporting the currently-supported Ruby versions, so I think we should reserve the right to drop support without warning for any EOL'ed Ruby as soon as it becomes a drag (or if we require newer features).

**Comment by timriley** [comment]
I wouldn't want us going further back than the most recent EOL'ed Ruby though.

**Comment by HoneyryderChuck** [comment]
Thx for considering this!

I think that officially supporting the latest-currently supported ruby is sane. However, "opportunistic support" should be a cheap target that is not hard to achieve.

As strategy, you could:

* Disclaim latest supported version in the README, while claiming that "it might work on other versions";
* Turn on CI for older rubies, but allow for failure (only from master branch, feature branches should only test supported versions); this will make it visible to potential users;
* Accept eventual patches from the community for backwards compatibility, within the limit of the reasonable; I don't think that the core team should be burdened by this, but there might be users which see value in this, and they should be responsible for implementing a solution that works, doesn't had much maintenance overhead, and can be easily removed in case it becomes too hard to maintain.

Even if you don't accept the 3rd, the other two suggestions are valid, I'd say.

I think this is important, as big applications don't change often, and adopting `dry-schema` gradually while validating with stakeholders should be independent of switching ruby versions, which have a larger footprint and must be therefore handled with care. All of this within the limit of reasonable (if you'd be using ruby 2.4-only features, I wouldn't be so persistent :) ).

**Comment by flash-gordon** [comment]
@HoneyryderChuck the goal is not to use latest ruby features but focus our efforts on what's worth to support. Usually, as time goes builds start to fail, it just happens. Occasionally, tuning CI takes a lot of time and it's natural to drop support for older versions since we don't rely on them. Frankly speaking, we have no idea who uses the gems and what ruby versions they run their code on, it's just sometimes someone show up with questions like this. This makes our communication mostly uni-directional. Unfortunately, this is even worse we have only one tool for that on hands, namely, `required_ruby_version` defined in gemspec file which creates obstacles for running code on earlier ruby versions even if it's theoretically possible. 

It'd be better to have support for overriding `required_ruby_version` on the rubygems/bundler side but it's not there :( We can replace `required_ruby_version` with a warning (issued from dry-core for example) when you load a gem in an environment which isn't tested/supported. WDYT? 
I'm still reluctant about running obsolete ruby versions on CI.

**Comment by solnic** [comment]
I don't want to run old versions on CI because it will be taking more time. Warning about an unsupported version of Ruby could do the trick but I suspect people will want to silence it anyway.

**Comment by HoneyryderChuck** [comment]
I'm fine with any solution that allows me to use lower rubies and lessens your maintenance burden. :)
