### ISSUE TITLE
Optional keys declared missing

### ISSUE THREAD

**Issue by flash-gordon** [dry-rb/dry-schema#87]
I have a schema with an optional key w/o bounds, dry-schema complains when it's not passed
```ruby
Dry::Schema.define { optional(:value) }.({})
#  => #<Dry::Schema::Result{} errors={:value=>["is missing"]}>
```
whereas adding any specification changes this behavior
```ruby
Dry::Schema.define { optional(:value).filled }.({})
# => #<Dry::Schema::Result{} errors={}>
```
I would expect `optional(:value)` to be enough in this case.

**Comment by solnic** [comment]
This is a funny case. Lack of a value rule makes it build a `key?` and since there's nothing in the trace, it just builds the default key rule. See here https://github.com/dry-rb/dry-schema/blob/3a919777f4186f0076592f359d3d5a85d2ffe737/lib/dry/schema/macros/key.rb#L91-L92

I wonder how to address this, should we build a default value rule that checks the type and allow `Any`?

**Comment by solnic** [comment]
Another idea is to REJECT rules for `optional` keys where there's no value rule. I think that's the best option because it will make things faster to process.

**Comment by flash-gordon** [comment]
yeah, check-wise it's useless, we only need to convert keys in this case
